# Using PyTorch to solve a linear regression problem from scratch

In [2]:
import numpy as np
import torch

In [3]:
#Input values
inputs = np.array([[73,67,43],
                   [91,88,64],
                   [87,134,58],
                   [102,43,37],
                   [69,96,70]], dtype='float32')

In [4]:
#Actual target values
targets = np.array([[56,70],
                    [81,101],
                    [119,133],
                    [22,37],
                    [103,119]], dtype='float32')

In [5]:
#covert numpy array to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [6]:
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [7]:
w = torch.randn(2,3,requires_grad=True)
b = torch.randn(2,requires_grad=True)
print(w)
print(b)

tensor([[-0.3658,  1.6638, -0.5992],
        [-0.7918, -0.5693, -1.1982]], requires_grad=True)
tensor([1.1520, 0.8294], requires_grad=True)


In [8]:
#Creating our model
def model(x):
  return x @ w.t() + b

In [9]:
#Making predictions
preds = model(inputs)
print(preds)

tensor([[  60.1563, -146.6406],
        [  75.9281, -198.0117],
        [ 157.5207, -213.8439],
        [  13.2123, -148.7497],
        [  93.6910, -192.3360]], grad_fn=<AddBackward0>)


In [10]:
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [11]:
#creating loss function MSE
def mse(t1,t2):
  diff = t1-t2
  return torch.sum(diff * diff) / diff.numel()

In [12]:
#compute loss
loss = mse(preds,targets)
print(loss)

tensor(38976.5625, grad_fn=<DivBackward0>)


##  The loss is higher , we'll use gradient descent to minimize the loss by adjusting the weights and biases.

In [14]:
#compute gradients
loss.backward()

In [15]:
print(w)
print(w.grad)

tensor([[-0.3658,  1.6638, -0.5992],
        [-0.7918, -0.5693, -1.1982]], requires_grad=True)
tensor([[   330.9023,    744.4784,    222.3100],
        [-22725.7812, -25036.1055, -15447.1006]])


In [16]:
print(b)
print(b.grad)

tensor([1.1520, 0.8294], requires_grad=True)
tensor([   3.9017, -271.9164])


In [17]:
#now we can reset the gradient back to zero
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


In [18]:
# Now trying to optimize predictions and minimize the loss using gradients
#Making predictions
preds = model(inputs)
print(preds)

tensor([[  60.1563, -146.6406],
        [  75.9281, -198.0117],
        [ 157.5207, -213.8439],
        [  13.2123, -148.7497],
        [  93.6910, -192.3360]], grad_fn=<AddBackward0>)


In [ ]:
loss = mse(preds,targets)

In [20]:
#compute gradients
loss.backward()
print(w.grad)
print(b.grad)

tensor([[   330.9023,    744.4784,    222.3100],
        [-22725.7812, -25036.1055, -15447.1006]])
tensor([   3.9017, -271.9164])


In [21]:
with torch.no_grad():
  w -= w.grad * 1e-5
  b -= b.grad * 1e-5
  w.grad.zero_()
  b.grad.zero_()

In [22]:
#checking the new weights and bias
print(w)
print(b)

tensor([[-0.3691,  1.6563, -0.6014],
        [-0.5645, -0.3190, -1.0438]], requires_grad=True)
tensor([1.1520, 0.8321], requires_grad=True)


In [24]:
#Making predictions again
preds = model(inputs)
loss = mse(preds,targets)
print(loss)

tensor(26387.7773, grad_fn=<DivBackward0>)


## We can see that there is a little decrement in the loss and new predictions are more accurate than previous predictions. Now we'll be training our model for 100 epochs.

In [31]:
# Training for multiple epochs
for i in range(100):
  preds = model(inputs)
  loss = mse(preds,targets)
  loss.backward()
  with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [32]:
#Checking the new predictions and actual targets
preds = model(inputs)
print(preds)
print(targets)

tensor([[ 57.9286,  71.6112],
        [ 75.0291,  94.7311],
        [133.7938, 144.3751],
        [ 23.6210,  43.0771],
        [ 88.1792, 105.4346]], grad_fn=<AddBackward0>)
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [33]:
# Checking new loss
loss = mse(preds,targets)
print(loss)

tensor(87.2747, grad_fn=<DivBackward0>)


Final predictions are much better than previous predictions and even the loss is lowered.